### ISSUE TITLE
Crash when using older version of pyftpdlibs

### ISSUE THREAD

**Issue by chmouel** [chmouel/ftp-cloudfs#3]
chmouel@lutece:GIT/perso/ftp-cloudfs$ ./bin/ftpcloudfs 

<pre>
2011-02-16 16:05:28,261 - INFO - Serving FTP on 127.0.0.1:2021
2011-02-16 16:05:35,152 - ERROR - Traceback (most recent call last):
  File "/usr/lib/python2.6/asyncore.py", line 78, in read
    obj.handle_read_event()
  File "/usr/lib/python2.6/asyncore.py", line 423, in handle_read_event
    self.handle_accept()
  File "/usr/lib/pymodules/python2.6/pyftpdlib/ftpserver.py", line 3260, in handle_accept
    handler = self.handler(sock, self)
  File "/usr/lib/pymodules/python2.6/pyftpdlib/ftpserver.py", line 1665, in __init__
    self.fs = self.abstracted_fs()
  File "/home/chmouel/Dropbox/GIT/perso/ftp-cloudfs/ftpcloudfs/server.py", line 184, in __init__
    super(RackspaceCloudFilesFS, self).__init__(*args, **kwargs)
TypeError: super() argument 1 must be type, not classobj

Traceback (most recent call last):
  File "./bin/ftpcloudfs", line 107, in <module>
    main()
  File "./bin/ftpcloudfs", line 103, in main
    ftpd.serve_forever()
  File "/usr/lib/pymodules/python2.6/pyftpdlib/ftpserver.py", line 3229, in serve_forever
    poll_fun(timeout, map)
  File "/usr/lib/python2.6/asyncore.py", line 127, in poll
    is_r = obj.readable()
  File "/usr/lib/pymodules/python2.6/pyftpdlib/ftpserver.py", line 1769, in readable
    return not self.sleeping and asynchat.async_chat.readable(self)
  File "/usr/lib/python2.6/asyncore.py", line 406, in __getattr__
    %(self.__class__.__name__, attr))
AttributeError: FTPHandler instance has no attribute 'sleeping'
</pre>

**Comment by reidrac** [comment]
Well, looks like we can close this :)
