### ISSUE TITLE
GitHub download URL don't play very well with PyPi

### ISSUE THREAD

**Issue by reidrac** [chmouel/ftp-cloudfs#9]
I'm trying to download a specific version of ftp-cloudfs from PyPI and seems to be impossible:

With python setup.py install:

```
....
Searching for ftp-cloudfs>=0.9
Reading http://pypi.python.org/simple/ftp-cloudfs/
Reading https://github.com/chmouel/ftp-cloudfs
Reading https://github.com/chmouel/ftp-cloudfs/zipball/0.7.1
Reading https://github.com/chmouel/ftp-cloudfs/zipball/0.9
Reading https://github.com/chmouel/ftp-cloudfs/zipball/0.7
Reading https://github.com/chmouel/ftp-cloudfs/zipball/0.5
No local packages or download links found for ftp-cloudfs>=0.9
error: Could not find suitable distribution for Requirement.parse('ftp-cloudfs>=0.9')
```

And Pip isn't upgrading it properly:

```
$ pip install --upgrade ftp-cloudfs
Downloading/unpacking ftp-cloudfs
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jjm/src/forks/ENV/lib/python2.7/site-packages/pip-0.7.2-py2.7.egg/pip/index.py", line 207, in _get_queued_page
    for link in page.rel_links():
  File "/home/jjm/src/forks/ENV/lib/python2.7/site-packages/pip-0.7.2-py2.7.egg/pip/index.py", line 439, in rel_links
    for url in self.scraped_rel_links():
  File "/home/jjm/src/forks/ENV/lib/python2.7/site-packages/pip-0.7.2-py2.7.egg/pip/index.py", line 466, in scraped_rel_links
    url = match.group(1) or match.group(2) or match.group(3)
IndexError: no such group

  Downloading ftp-cloudfs-0.7.1.tar.gz
  Running setup.py egg_info for package ftp-cloudfs

Downloading/unpacking pyftpdlib (from ftp-cloudfs)
  Downloading pyftpdlib-0.6.0.tar.gz (128Kb): 128Kb downloaded
  Running setup.py egg_info for package pyftpdlib

Downloading/unpacking python-cloudfiles (from ftp-cloudfs)
  Downloading python-cloudfiles-1.7.9.1.tar.gz (118Kb): 118Kb downloaded
  Running setup.py egg_info for package python-cloudfiles

    warning: no previously-included files found matching 'python_cloudfiles.egg-info'
Installing collected packages: ftp-cloudfs, pyftpdlib, python-cloudfiles
  Found existing installation: ftp-cloudfs 0.8
    Not uninstalling ftp-cloudfs at /usr/lib/python2.7/dist-packages, outside environment /home/jjm/src/forks/ENV
  Running setup.py install for ftp-cloudfs

    changing mode of build/scripts-2.7/ftpcloudfs from 644 to 755
    changing mode of /home/jjm/src/forks/ENV/bin/ftpcloudfs to 755
  Found existing installation: pyftpdlib 0.6.0
    Not uninstalling pyftpdlib at /usr/lib/python2.7/dist-packages, outside environment /home/jjm/src/forks/ENV
  Running setup.py install for pyftpdlib

  Running setup.py install for python-cloudfiles

    warning: no previously-included files found matching 'python_cloudfiles.egg-info'
Successfully installed ftp-cloudfs pyftpdlib python-cloudfiles
Cleaning up...
```

So it's installing 0.7.1 instead of 0.9 (current installed version is 0.8).

I'm not sure, but uploading sdist to PyPi may fix the problem (?).

**Comment by reidrac** [comment]
The problem is probably that the ZIP file we download from GitHub it's not a proper PyPi distribution file (metadata is missing), and that's why isn't going to work.

I would upload a sdist file (at least) to PyPi.

**Comment by chmouel** [comment]
Hello I am not sure why it wasn't working this time: used python setup.py sdist upload  instead of setup.py register for uploading the tarball with new version. fixed the download URL as well in fdc5f3a

**Comment by chmouel** [comment]
Will need probably a new version before it's properly fixed, let me know if you want me to do that when you guys release new fix/release.

**Comment by reidrac** [comment]
It's OK! I've tried it without that URL fix and now it works like a charm, thanks!

I think that easy_tools looks for the package on PyPi by default, and that one has the metadata needed to install the source. So the key is the "python setup.py sdist upload", unless we can host a sdist tgz on GitHub (which is inconvenient, because it can't be generated just adding a tag on git!).

```
...
Searching for ftp-cloudfs>=0.9
Reading http://pypi.python.org/simple/ftp-cloudfs/
Reading https://github.com/chmouel/ftp-cloudfs
Reading https://github.com/chmouel/ftp-cloudfs/zipball/0.7.1
Reading https://github.com/chmouel/ftp-cloudfs/zipball/0.9
Reading https://github.com/chmouel/ftp-cloudfs/zipball/0.7
Reading https://github.com/chmouel/ftp-cloudfs/zipball/0.5
Best match: ftp-cloudfs 0.9
Downloading http://pypi.python.org/packages/source/f/ftp-cloudfs/ftp-cloudfs-0.9.tar.gz#md5=5d928dc970b4e5a062044c022c619bd0
...
```
